site_name: MeshCore Docs
site_url: https://meshcore-dev.github.io/meshcore/
site_description: Documentation for the open source MeshCore firmware

repo_name: meshcore-dev/meshcore
repo_url: https://github.com/meshcore-dev/meshcore/
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _assets/meshcore.svg
  features:
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.suggest

extra_css:
  - _stylesheets/extra.css

nav:
  - Introduction: index.md
  - FAQ: faq.md
  - CLI Commands: cli_commands.md
  - Companion Protocol: companion_protocol.md
  - Terminal Chat CLI: terminal_chat_cli.md
  - KISS Modem Protocol: kiss_modem_protocol.md
  - Reference:
      - Core Library Architecture: architecture.md
      - Packet Format: packet_format.md
      - Payloads: payloads.md
      - Number Allocations: number_allocations.md
      - Stats Binary Frames: stats_binary_frames.md
      - QR Codes: qr_codes.md
      - nRF52 Power Management: nrf52_power_management.md
  - Building These Docs: docs.md
